[project]
authors = ["Trey Stafford <trey.stafford@colorado.edu>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pixi-fail"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test = { cmd = "pytest ../", cwd = "./src" }

[dependencies]
python = ">=3.12.4,<4"
pytest = ">=8.3.2,<9"
numpy = ">=2.0.1,<3"
